apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-portals-config
data:
  {{ if .Values.webPortals }}
  {{ if .Values.webPortals.releasedAt }}
  APPLICATION_RELEASEDAT: {{ .Values.webPortals.releasedAt }}
  {{ end }}
  {{ end }}
  {{ if or .Values.certmanager.enabled .Values.ingress.forceHttpsRedirect }}
  WEB_API_BASE_URL: https://{{ .Values.ingress.hosts.webApiHost }}
  RELEASE_SERVER_BASE_URL: https://{{ .Values.ingress.hosts.releaseServerHost }}
  {{ else }}
  WEB_API_BASE_URL: http://{{ .Values.ingress.hosts.webApiHost }}
  RELEASE_SERVER_BASE_URL: http://{{ .Values.ingress.hosts.releaseServerHost }}
  {{ end }}
