apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-api-secret
type: Opaque
stringData:
  {{ if .Values.services.database.external }}
  DATABASE_URL: {{ .Values.webApi.databaseUrl }}
  DATABASE_READERURL: {{ .Values.webApi.databaseReaderUrl | quote }}
  {{ else }}
  DATABASE_URL: postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Release.Name }}-database-service:5432/{{ .Values.database.name }}
  {{ end }}
  {{ if .Values.webApi.tenantDatabaseClusters }}
  {{ range $index, $value := .Values.webApi.tenantDatabaseClusters }}
  TENANTDATABASECLUSTERS_{{$index}}_USERNAME: {{ $value.username | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_PASSWORD: {{ $value.password | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_HOST: {{ $value.host | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_READERHOST: {{ $value.readerHost | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_PORT: {{ default 5432 $value.port | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_DATABASE: {{ $value.database | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_MAXIMUMPOOLSIZE: {{ default 300 $value.maximumPoolSize | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_DATABASECLUSTERID: {{ $value.databaseClusterId | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_ENABLESSL: {{ $value.enableSsl | quote }}
  TENANTDATABASECLUSTERS_{{$index}}_ALLOWNEWTENANTS: {{ $value.allowNewTenants | quote }}
  {{ end }}
  {{ end }}
  {{ if .Values.services.cache.external }}
  REDIS_URL: {{ .Values.webApi.redis.url | quote }}
  {{ else }}
  REDIS_URL: redis://{{ .Release.Name }}-cache-service:6379
  {{ end }}
  ENCRYPTION_KEY: {{ .Values.webApi.encryptionKey | default .Values.webApi.rsaPassphrase | quote }}
  RSA_PASSPHRASE: {{ .Values.webApi.rsaPassphrase }}
  {{ if .Values.webApi.jwtRsaPublicKey }}
  JWT_RSA_PUBLICKEY: {{ .Values.webApi.jwtRsaPublicKey | quote }}
  {{ end }}
  {{ if .Values.webApi.jwtSecret }}
  JWT_SECRETKEY: {{ .Values.webApi.jwtSecret | quote }}
  {{ end }}
  {{ if .Values.services.rabbitMq.external }}
  RABBITMQ_URL: {{ .Values.webApi.rabbitMq.url | quote }}
  RABBITMQ_USERNAME: {{ .Values.webApi.rabbitMq.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.webApi.rabbitMq.password | quote }}
  {{ else }}
  RABBITMQ_URL: amqps://{{ .Release.Name }}-rabbitmq:5672
  RABBITMQ_USERNAME: {{ .Values.rabbitMq.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitMq.password | quote }}
  {{ end }}
  HANGFIREDASHBOARD_USERNAME: {{ .Values.webApi.hangfireDashboard.username | quote }}
  HANGFIREDASHBOARD_PASSWORD: {{ .Values.webApi.hangfireDashboard.password | quote }}
  SMTP_USERNAME: {{ .Values.webApi.email.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.webApi.email.smtp.password | quote }}
  MAILGUN_APIKEY: {{ .Values.webApi.email.mailgun.apiKey | quote }}
  POSTMARK_ACCOUNTTOKEN: {{ .Values.webApi.postmark.accountToken | quote }}
  SENDGRID_APIKEY: {{ .Values.webApi.email.sendgrid.apiKey | quote }}
  GOOGLE_RECAPTCHA_SECRETKEY: {{ .Values.webApi.google.recaptcha.secretKey | quote }}
  BUGSNAG_APIKEY: {{ .Values.webApi.bugsnag.apiKey | quote }}
  {{ if .Values.webApi.fly }}
  {{ if .Values.webApi.fly.apiKey }}
  FLY_APIKEY: {{ .Values.webApi.fly.apiKey | quote }}
  {{ end }}
  {{ end }}
  {{ if .Values.webApi.stripe }}
  {{ if .Values.webApi.stripe.secretKey }}
  STRIPE_SECRETKEY: {{ .Values.webApi.stripe.secretKey | quote }}
  {{ end }}
  {{ end }}
  {{ if .Values.webApi.paddle }}
  {{ if .Values.webApi.paddle.vendorId }}
  PADDLE_VENDORID: {{ .Values.webApi.paddle.vendorId | quote }}
  {{ end }}
  {{ if .Values.webApi.paddle.vendorAuthCode }}
  PADDLE_VENDORAUTHCODE: {{ .Values.webApi.paddle.vendorAuthCode | quote }}
  {{ end }}
  {{ if .Values.webApi.paddle.apiKey }}
  PADDLE_APIKEY: {{ .Values.webApi.paddle.apiKey | quote }}
  {{ end }}
  {{ end }}
  {{ if .Values.webApi.posthog }}
  {{ if .Values.webApi.posthog.apiKey }}
  POSTHOG_APIKEY: {{ .Values.webApi.posthog.apiKey | quote }}
  {{ end }}
  {{ end }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.webApi.newRelic.licenseKey | quote }}
  OTEL_EXPORTER_OTLP_HEADERS: "{{- range $index, $header := .Values.webApi.openTelemetry.otlpHeaders -}}
    {{- if $index }}, {{ end -}}
    {{- range $key, $value := $header }}
      {{ $key }}={{ $value }}
    {{ end -}}
  {{- end }}"